kind: ConfigMap
apiVersion: v1
metadata:
  name: innodb-mycnf
  namespace: mysql
data:
  my.cnf: |-
    [mysqld]
    skip-host-cache
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/lib/mysql/mysql.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql

    pid-file=/var/run/mysqld/mysqld.pid
    early-plugin-load = keyring_file.so
    keyring_file_data = /var/lib/mysql/mysql_keyring/keyring

    ### innodb_buffer_pool_size=12884901888
    max_connections=1000
    default-time-zone='+05:30'
 
    bind-address=*
    require_secure_transport=ON

    [client]
    ssl-ca=/var/lib/mysql/ca.pem
    ssl-cert=/var/lib/mysql/client-cert.pem
    ssl-key=/var/lib/mysql/client-key.pem
